all:
	cargo run --example hello_rtic --features swtasks
	cargo run --example async_ping_pong --features async
# 	cargo run --example async_monotonic --features async # disabled because qemu doesn't support timers yet.