[package]
name = "rticx_riscv_example_slic"
version = "0.1.0"
edition = "2024"
publish = false

[[example]]
name = "hello_rtic"
path = "examples/hello_rtic.rs"

[dependencies]
rticx-riscv = { path = "../../", default-features = false, features = [
    "slic",
    "swtasks",
] }
# rticx-riscv = { path = "../../", default-features = false, features = ["slic", "mecall-backend", "swtasks"] }
hifive1 = { version = "0.13.0", features = ["board-redv"] }
riscv-rt = { version = "0.13.0", features = ["single-hart"] }
riscv = "0.12.1"
semihosting = { version = "0.1", features = ["stdio", "panic-handler"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = "s"

[features]
default = ["slic-clint-backend"]
slic-clint-backend = ["rticx-riscv/clint-backend"]
slic-mecall-backend = ["rticx-riscv/mecall-backend"]
